'use strict';

const { app, BrowserWindow, utilityProcess, dialog } = require('electron');
const path = require('path');
const http = require('http');
const fs = require('fs');

let serverProcess = null;
let mainWindow = null;
let loadingWindow = null;

// ── Path helpers ──────────────────────────────────────────────────────────────

function getServerScript() {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, 'server', 'index.js');
  }
  return path.join(__dirname, '..', 'server', 'index.js');
}

function getServerCwd() {
  if (app.isPackaged) {
    // Production: redirect data writes to a user-writable location.
    // We write a thin bootstrap that patches path.join for the three data dirs
    // (uploads/, vector_index/, feedback.json) before loading the real server.
    return path.join(process.resourcesPath, 'server');
  }
  return path.join(__dirname, '..', 'server');
}

// In production the server's __dirname points to read-only resources.
// We write a tiny bootstrap to userData that redirects those three write paths
// before requiring the real server — without touching server source.
function ensureProductionBootstrap() {
  const userData = app.getPath('userData');
  const serverDir = path.join(process.resourcesPath, 'server');
  const dataDir = path.join(userData, 'edusaku-data');

  // Create writable data dirs
  for (const sub of ['uploads', 'vector_index']) {
    const dir = path.join(dataDir, sub);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  }

  const bootstrapPath = path.join(userData, 'edusaku-bootstrap.js');
  const content = `'use strict';
// Auto-generated by Edusaku Electron main.js — do not edit.
const path = require('path');
const serverDir = ${JSON.stringify(serverDir)};
const dataDir = ${JSON.stringify(dataDir)};

// Redirect write-path calls (uploads, vector_index, feedback.json) to writable userData.
const _origJoin = path.join.bind(path);
path.join = function (...args) {
  const result = _origJoin(...args);
  if (result === _origJoin(serverDir, 'uploads')) return _origJoin(dataDir, 'uploads');
  if (result === _origJoin(serverDir, 'vector_index')) return _origJoin(dataDir, 'vector_index');
  if (result === _origJoin(serverDir, 'feedback.json')) return _origJoin(dataDir, 'feedback.json');
  return result;
};

require(${JSON.stringify(path.join(serverDir, 'index.js'))});
`;

  fs.writeFileSync(bootstrapPath, content, 'utf8');
  return bootstrapPath;
}

// ── Windows ───────────────────────────────────────────────────────────────────

function createLoadingWindow() {
  loadingWindow = new BrowserWindow({
    width: 480,
    height: 300,
    frame: false,
    resizable: false,
    center: true,
    alwaysOnTop: true,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });
  loadingWindow.loadFile(path.join(__dirname, 'loading.html'));
}

function createMainWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    show: false,
    title: 'Edusaku',
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  mainWindow.loadURL('http://localhost:3000');

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
    if (loadingWindow && !loadingWindow.isDestroyed()) {
      loadingWindow.close();
      loadingWindow = null;
    }
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ── Server polling ────────────────────────────────────────────────────────────

function pollServer(maxAttempts, intervalMs) {
  return new Promise((resolve, reject) => {
    let attempts = 0;

    function attempt() {
      attempts++;
      const req = http.get('http://localhost:3000/ping', (res) => {
        if (res.statusCode === 200) {
          resolve();
        } else if (attempts >= maxAttempts) {
          reject(new Error(`Server returned HTTP ${res.statusCode}`));
        } else {
          setTimeout(attempt, intervalMs);
        }
        // drain response body
        res.resume();
      });

      req.on('error', () => {
        if (attempts >= maxAttempts) {
          reject(new Error('Server did not start in time'));
        } else {
          setTimeout(attempt, intervalMs);
        }
      });

      req.setTimeout(1000, () => {
        req.destroy();
        if (attempts >= maxAttempts) {
          reject(new Error('Server timed out'));
        } else {
          setTimeout(attempt, intervalMs);
        }
      });
    }

    setTimeout(attempt, intervalMs);
  });
}

// ── App lifecycle ─────────────────────────────────────────────────────────────

app.whenReady().then(async () => {
  createLoadingWindow();

  let scriptPath;
  let cwd;

  if (app.isPackaged) {
    scriptPath = ensureProductionBootstrap();
    cwd = app.getPath('userData');
  } else {
    scriptPath = getServerScript();
    cwd = getServerCwd();
  }

  // Fork the Express server using Electron's bundled Node.js runtime.
  // utilityProcess.fork does not require a separate Node installation.
  serverProcess = utilityProcess.fork(scriptPath, [], {
    cwd,
    stdio: 'pipe',
    env: { ...process.env },
  });

  serverProcess.stdout.on('data', (data) => {
    process.stdout.write('[server] ' + data);
  });
  serverProcess.stderr.on('data', (data) => {
    process.stderr.write('[server] ' + data);
  });
  serverProcess.on('exit', (code) => {
    console.log('[electron] server process exited with code', code);
  });

  try {
    // Poll every 500ms for up to 90 seconds (180 attempts)
    await pollServer(180, 500);
    createMainWindow();
  } catch (err) {
    console.error('[electron] Server failed to start:', err.message);
    if (loadingWindow && !loadingWindow.isDestroyed()) {
      loadingWindow.webContents.executeJavaScript(
        `document.getElementById('status').textContent = 'Failed to start server. Please check the logs.';
         document.getElementById('spinner').style.display = 'none';`
      );
    }
    dialog.showErrorBox(
      'Edusaku — Startup Failed',
      `The server did not start in time.\n\n${err.message}\n\nPlease ensure Node.js is installed and try again.`
    );
  }
});

app.on('will-quit', () => {
  if (serverProcess) {
    serverProcess.kill();
    serverProcess = null;
  }
});

app.on('window-all-closed', () => {
  // On macOS the convention is to keep the app running until explicitly quit
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On macOS re-open the window when the dock icon is clicked and no windows are open
  if (mainWindow === null) {
    createMainWindow();
  }
});
